/// Flutter icons MeetupIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MeetupIcons
///      fonts:
///       - asset: fonts/MeetupIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MeetupIcons {
  MeetupIcons._();

  static const _kFontFam = 'MeetupIcons';
  static const String? _kFontPkg = null;

  static const IconData youtube = IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData times_light = IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars_light = IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
